### PR TITLE
fix(#8664): fix angular change detection bug in mobile

### LINKED ISSUE #8664: Expression changed after it was checked Error in Reports component
**Describe the bug**
When running dev build and running default mobile e2e tests, tests that deal with deleting reports fail because of an `ExpressionChangedAfterItHasBeenCheckedError`. 

**To Reproduce**
1. `npm run build-dev`
2. `npm run default-wdio-mobile-local`
3. report delete tests fail because of generated feedback docs: 
```
{
      "_id": "feedback-2023-10-25T11:37:26.714Z-8b1cf8a5-b3cf-4ac8-bca3-cb8eecbcb55d",
      "_rev": "1-fb9e69fdb539c346e8c38a4a09a23edd",
      "info": {
        "message": "NG0100: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: '0'. Current value: '1'. Expression location: ReportsComponent component. Find more at https://angular.io/errors/NG0100",
        "stack": "Error: NG0100: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: '0'. Current value: '1'. Expression location: ReportsComponent component. Find more at https://angular.io/errors/NG0100\n    at throwErrorIfNoChangesMode (https://localhost/main.js:241807:9)\n    at bindingUpdated (https://localhost/main.js:244920:9)\n    at pureFunction1Internal (https://localhost/main.js:253360:10)\n    at Module.ɵɵpureFunction1 (https://localhost/main.js:253169:10)\n    at ReportsComponent_Template (https://localhost/main.js:24114:213)\n    at executeTemplate (https://localhost/main.js:242190:7)\n    at refreshView (https://localhost/main.js:243617:7)\n    at detectChangesInView (https://localhost/main.js:243779:5)\n    at detectChangesInComponent (https://localhost/main.js:243757:3)\n    at detectChangesInChildComponents (https://localhost/main.js:243791:5)"
      },
      "log": [
        {
          "arguments": "[\"Initiating changes watch (meta=true)\"]",
          "level": "info",
          "time": "2023-10-25T11:37:26.709Z"
        },
        {
          "arguments": "[\"Initiating changes watch (meta=false)\"]",
          "level": "info",
          "time": "2023-10-25T11:37:26.708Z"
        },
        {
          "arguments": "[\"Error: NG0100: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: '0'. Current value: '1'. Expression location: ReportsComponent component. Find more at https://angular.io/errors/NG0100\\n    at throwErrorIfNoChangesMode (https://localhost/main.js:241807:9)\\n    at bindingUpdated (https://localhost/main.js:244920:9)\\n    at pureFunction1Internal (https://localhost/main.js:253360:10)\\n    at Module.ɵɵpureFunction1 (https://localhost/main.js:253169:10)\\n    at ReportsComponent_Template (https://localhost/main.js:24114:213)\\n    at executeTemplate (https://localhost/main.js:242190:7)\\n    at refreshView (https://localhost/main.js:243617:7)\\n    at detectChangesInView (https://localhost/main.js:243779:5)\\n    at detectChangesInComponent (https://localhost/main.js:243757:3)\\n    at detectChangesInChildComponents (https://localhost/main.js:243791:5)\"]",
          "level": "error",
          "time": "2023-10-25T11:37:26.692Z"
        },
        {
          "arguments": "[\"%c next state\",\"color: #4CAF50; font-weight: bold\",{\"global\":{\"actionBar\":{\"left\":{},\"right\":{}},\"navigation\":{\"cancelCallback\":null,\"preventNavigation\":null,\"cancelTranslationKey\":null,\"recordTelemetry\":null},\"currentTab\":\"reports\",\"snapshotData\":{\"permissions\":[\"can_view_reports\"],\"tab\":\"reports\",\"name\":\"reports.detail\"},\"enketoStatus\":{\"form\":false,\"edited\":false,\"saving\":false,\"error\":null},\"facilities\":[],\"filters\":{\"search\":\"\"},\"sidebarFilter\":{},\"forms\":null,\"lastChangedDoc\":false,\"loadingContent\":false,\"loadingSubActionBar\":false,\"replicationStatus\":{\"disabled\":false,\"lastSuccessTo\":1698233844584},\"selectMode\":false,\"privacyPolicyAccepted\":true,\"showActionBar\":false,\"showContent\":false,\"showPrivacyPolicy\":false,\"title\":\"\",\"unreadCount\":{},\"version\":null,\"snackbarContent\":null,\"translationsLoaded\":true,\"userFacilityId\":null,\"trainingCardFormId\":null},\"services\":{\"lastChangedDoc\":false},\"analytics\":{\"selected\":null,\"analyticsModules\":[{\"id\":\"targets\",\"label\":\"analytics.targets\"",
          "level": "log",
          "time": "2023-10-25T11:37:26.681Z"
        },
```

**Environment**
- Instance: local test
- Browser: chrome
- App: webapp
- Version: 4.4 

**Additional context**
The issue also affects production builds, but the error won't be logged in this case and the effects will be visible - because there is no double rendering cycle.

### PR DESCRIPTION
**Pull request by Benmuiruri**
# Description

My investigation into the issue suggested the problem was caused by changes from `ResponsiveService.isMobile()` not being captured correctly by Angular's change detection. 

This fix is to remove `getFastActionButtonType()`  that dynamically sets the FAB for mobile and desktop. Instead of doing it dynamically, we can use CSS to determine which FAB button to show. 

closes #8664 

# Code review checklist

- [ ] Readable: Concise, well named, follows the [style guide](https://docs.communityhealthtoolkit.org/contribute/code/style-guide/), documented if necessary.
- [ ] Documented: Configuration and user documentation on [cht-docs](https://github.com/medic/cht-docs/)
- [ ] Tested: Unit and/or e2e where appropriate
- [ ] Internationalised: All user facing text
- [ ] Backwards compatible: Works with existing data and configuration or includes a migration. Any breaking changes documented in the release notes.

# Compose URLs
If Build CI hasn't passed, these may 404:

* [Core](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8664-bug-fix/docker-compose/cht-core.yml)
* [CouchDB Single](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8664-bug-fix/docker-compose/cht-couchdb.yml)
* [CouchDB Cluster](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:8664-bug-fix/docker-compose/cht-couchdb-clustered.yml)

# License

The software is provided under AGPL-3.0. Contributions to this project are accepted under the same license.

### CODE REVIEW

File: webapp/src/ts/modules/reports/reports.component.ts [hunk 1]
```diff
@@ -190,6 +194,14 @@ export class ReportsComponent implements OnInit, AfterViewInit, OnDestroy {
     this.subscription.add(subscription);
   }
 
+  private subscribeToResponsiveChanges() {
+    const responsiveSubscription = this.responsiveService.viewportChanged$.subscribe(() => {
+      this.getFastActionButtonType();
+      this.changeDetectorRef.detectChanges();
```
Comment (latin-panda) [inline webapp/src/ts/modules/reports/reports.component.ts:200]: Is there another way? We avoid using `this.changeDetectorRef.detectChanges();` because it gives performance overhead and can get stuck in change detection loops and risk undesired behaviors because it breaks Angular's detection change cycle. 

It exists for some special cases where people handle the detection change manually, which we don't

Comment (Benmuiruri) [reply webapp/src/ts/modules/reports/reports.component.ts:200]: The other solution I see is using Angular's [AsyncPipe](https://angular.dev/api/common/AsyncPipe?tab=description) in the template. We use the `responsiveService.viewportChanged$` observable then update the template when value changes.

```
<mm-fast-action-button
  [config]="{ button: { type: fastActionButtonType$ | async } }"
  [fastActions]="fastActionList">
</mm-fast-action-button>
```

Comment (latin-panda) [reply webapp/src/ts/modules/reports/reports.component.ts:200]: I found an alternative that reduces complexity (having fewer observables) and relies on CSS more. I just did it for reports, and if it works, then we need to do it for the Message and Contact pages

https://github.com/medic/cht-core/tree/angular-exeption-in-fab

Give it a try, and please let me know what you think

Comment (Benmuiruri) [reply webapp/src/ts/modules/reports/reports.component.ts:200]: Yes that worked and is a MUCH SIMPLER solution. We also need to add the following to `@media (max-width: @media-mobile) {}`

```
.mobile-only {
    display: initial;
  }
  .desktop-only {
    display: none;
  }
  ```

Comment (latin-panda) [reply webapp/src/ts/modules/reports/reports.component.ts]: Maybe double-check where those classes are currently used, in case they were intentionally skipped from `@media (max-width: @media-mobile) {}`

Comment (Benmuiruri) [reply webapp/src/ts/modules/reports/reports.component.ts]: I've checked where the classes are used, compared with master ... adding the classes in mobile does not change behavior. 

But without them, we get the wrong button 

Screenshot 2024-08-30 at 11 50 59

Comment (latin-panda) [reply webapp/src/ts/modules/reports/reports.component.ts]: Thanks for checking Ben!

**Review by latin-panda — APPROVED** [review]
Awesome! Code looks good!

**Review by tatilepizs — APPROVED** [review]
Thank you for the fix Ben! ⭐

**Comment by Benmuiruri** [comment]
Hi @tatilepizs maybe you can help me with this failing CI ? 

- The `ci-webdriver-default-mobile-all` test is consistently failing. In particular the `hamburger-menu.wdio-spec.js` test is failing. 
- Locally the test is passing in this branch and in master
- I have rebased with Master, I see the test is passing in master but not in this branch. 

Can you see something I am missing ?

**Comment by tatilepizs** [comment]
@Benmuiruri it is a real error, I am not sure what is causing it, but when you open a hamburger menu, in the mobile view, the `App Management` option is not displayed in your branch, but it is working fine in `master`.


[video](https://github.com/user-attachments/assets/49e706a0-58f1-4e0d-b073-2f172f548570)

**Comment by tatilepizs** [comment]
I don't know if this is helpful 😅 but I was trying to identify what might cause the problem, so I started to comment your changes, and if I comment [the changes in the `inbox.less` file](https://github.com/medic/cht-core/blob/8664-bug-fix/webapp/src/css/inbox.less#L1463-L1468) I can see the `App Management` section again.


[video](https://github.com/user-attachments/assets/599bd1a4-2be9-4065-8f2d-ad8073b0319c)

**Comment by Benmuiruri** [comment]
Thanks Tatiana, you're a rockstar. I'll take it up tomorrow.

**Review by tatilepizs — APPROVED** [review]
Thank you Ben!! 🚀

File: webapp/src/ts/modules/messages/messages.component.html
Comment (latin-panda) [inline webapp/src/ts/modules/messages/messages.component.html:1]: @Benmuiruri do we need to do the same fix in contacts.component?

File: webapp/src/css/inbox.less [hunk 2]
```diff
@@ -1157,6 +1157,10 @@ a.fa:hover {
   display: none;
 }
 
+.mobile-fab {
```
Comment (latin-panda) [inline webapp/src/css/inbox.less:1160]: Not saying to change it, but another alternative is: 
```
mm-fast-action-button.desktop-only {........}
mm-fast-action-button.mobile-only {........}
```
