### PR TITLE
fix(#9799): add user-agent header to outbound

### LINKED ISSUE #9799: Allow configuring headers in outbound push
Outbound push may sometimes require different HTTP headers such as User-Agent; currently its not possible to add or change HTTP headers other than authorization.

Allow headers to be added or changed in configuration like
```
        "headers": {
          "User-Agent": "CHT-Integration/1.0 libwww/2.17b3"
        },
```

### PR DESCRIPTION
**Pull request by witash**
adds user-agent header to outbound
User-Agent headers should include versions, which means a little extra stuff; it tries to get the CHT version in the same way as api/src/services/deploy-info.js, but that code is not directly available from shared-libs, so there is some small duplication. 
Added getVersion() to shared-libs/settings. It doesn't quite fit there, but I don't think its worth it to make another separate shared-lib

We could also just omit the version if it adds too much mess, but I think these small additions are ok.

closes #9799

### CODE REVIEW

**Review by dianabarsan — COMMENTED** [review]
Such a quick turnaround! nice! 
I left some minor suggestions inline.

**Comment by gitcliff** [comment]
hello @dianabarsan @witash should we upgrade to this branch in the UI in the meantime as the work here still goes on ?

**Comment by witash** [comment]
@dianabarsan this is ready for re-reivew, moved deploy-info to shared-libs/environment so it could be used in both the API and other shared-libs, and refactored outbound.js to use aysnc/await instead of explicit Promises.

@gitcliff I think it should be ok to upgrade your instance to this branch temporarily

File: shared-libs/environment/src/index.js [hunk 1]
```diff
@@ -57,5 +63,48 @@ try {
...
+const getDeployInfo = async () => {
+  if (deployInfoCache) {
+    return deployInfoCache;
+  }
+
+  let ddoc;
+  try {
+    ddoc = await request.get({
+      url: `${couchUrl}/_design/${module.exports.ddoc}`,
+      json: true
```
Comment (dianabarsan) [inline shared-libs/environment/src/index.js:84]: This should not be required (it should be enabled by default).

File: shared-libs/environment/src/index.js [hunk 2]
```diff
@@ -57,5 +63,48 @@ try {
...
+};
+
+const getDeployInfo = async () => {
+  if (deployInfoCache) {
+    return deployInfoCache;
+  }
+
+  let ddoc;
+  try {
+    ddoc = await request.get({
```
Comment (dianabarsan) [inline shared-libs/environment/src/index.js:82]: I believe `ddoc` can be a scoped `const` here, and we can return within the try-catch block.

File: shared-libs/environment/test/index.spec.js [hunk 3]
```diff
@@ -38,7 +39,7 @@ describe('environment', () => {
 
     const env = rewire('../src/index');
 
-    expect(env).to.deep.equal({
+    expect(env).to.deep.include({
```
Comment (dianabarsan) [inline shared-libs/environment/test/index.spec.js:42]: I think we should keep the strict `equal` test here, and be definitive of which properties should be exported, and we can use `chai-exclude` to exclude the functions.

File: shared-libs/outbound/src/outbound.js [hunk 4]
```diff
@@ -92,101 +95,118 @@ const mapDocumentToPayload = (doc, config, key) => {
...
+    await handleMusoSihAuth(authConf, config, sendOptions);
+  }
+};
+
+// Attempts to send a given payload using a given push config
+const sendPayload = async (payload, config) => {
+  const sendOptions = {
+    url: urlJoin(config.destination.base_url, config.destination.path),
+    body: payload,
+    json: true,
```
Comment (dianabarsan) [inline shared-libs/outbound/src/outbound.js:186]: `json` is `true` by default.

File: shared-libs/outbound/src/outbound.js [hunk 5]
```diff
@@ -92,101 +95,118 @@ const mapDocumentToPayload = (doc, config, key) => {
...
-  return auth().then(() => {
-    if (logger.isDebugEnabled()) {
-      logger.debug('About to send outbound request');
-      const clone = JSON.parse(JSON.stringify(sendOptions));
-      if (clone.auth && clone.auth.password) {
-        // mask password before logging
-        clone.auth.password = '*****';
-      }
-      logger.debug(JSON.stringify(clone, null, 2));
+  sendOptions.headers['user-agent'] = await getUserAgent();
```
Comment (dianabarsan) [inline shared-libs/outbound/src/outbound.js:191]: Why not add this directly when declaring `sendOptions`?

**Review by dianabarsan — COMMENTED** [review]
Very nice. Just some minor comments here.

File: shared-libs/outbound/src/outbound.js [hunk 6]
```diff
@@ -16,22 +16,25 @@ const urlJoin = require('url-join');
...
-    return password;
-  });
+const CHT_AGENT = 'CHT';
+
+const fetchPassword = async key => {
+  const password = await secureSettings.getCredentials(key);
+  if (!password) {
+    throw new OutboundError(
+      `Credentials for '${key}' have not been configured. See the Outbound documentation.`
+    );
```
Comment (gitcliff) [inline shared-libs/outbound/src/outbound.js:35]: hello @witash been testing this out and what is the sample payload for this new refactoring i am hitting this error message with an outbound payload like 
```
 "patient triggers enroll workflow in Textit": {
      "relevant_to": "doc.type === 'person' && doc.docket",
      "destination": {
        "base_url": "https://textit.com",
        "auth": {
          "type": "header",
          "name": "Authorization",
          "value_key": "rapidpro.api"
        },
        "headers": {
          "User-Agent": "CHT/4.17.0"
        },
        "path": "/api/v2/flow_starts.json"
      },
      "mapping": {
        "flow": {
          "expr": "'650567d6-6662-4c0e-9ea3-98eba8ef'"
        },
        "urns": {
          "expr": "['tel:' + doc.phone]"
        }
      }
    },

```
Error log `2025-03-03T20:28:13.381 ERROR: Failed to push 356ffef1-29d8-44a7-8861-dc5d3637 to patient triggers enroll workflow in Textit: Credentials for 'rapidro.api' have not been configured. See the Outbound documentation. 
`

**Comment by andrablaj** [comment]
Per our discussion today, @witash, re-requesting a review from @dianabarsan

File: shared-libs/environment/test/index.spec.js [hunk 7]
```diff
@@ -74,4 +80,98 @@ describe('environment', () => {
...
+
+        const result = await env.getDeployInfo();
+        expect(result).to.deep.equal({
+          version: '4.1.0',
+          date: '2023-01-01',
+          base_version: '4.0.0',
+          timestamp: '2023-01-02'
+        });
+        expect(request.get.callCount).to.equal(1);
+        expect(request.get.args[0][0].url).to.equal('http://admin:pass@localhost:5984/medicdb/_design/medic');
```
Comment (dianabarsan) [inline shared-libs/environment/test/index.spec.js:119]: I think we should be more strict about the assertion here, and assert all params that are passed to request.get. 
We could easily make a `DELETE` request and the test would still pass

File: shared-libs/environment/test/index.spec.js [hunk 8]
```diff
@@ -74,4 +80,98 @@ describe('environment', () => {
...
+        expect(request.get.callCount).to.equal(1);
+      });
+
+      it('should throw error if request fails', async () => {
+        sinon.stub(request, 'get').rejects(new Error('Failed to fetch'));
+        sinon.stub(logger, 'error');
+
+        const env = rewire('../src/index');
+
+        try {
```
Comment (dianabarsan) [inline shared-libs/environment/test/index.spec.js:144]: A nicer way to assert on calls we know will fail is do something like: 
```suggestion
await expect(env.getDeployInfo()).to.eventually.be.rejectedWith('Failed to fetch');
```

This requires `chai.use(require('chai-as-promised''))`; you should be able to find examples of usage throughout our codebase.

File: shared-libs/outbound/test/outbound.spec.js [hunk 9]
```diff
@@ -340,10 +341,7 @@ describe('outbound shared library', () => {
           assert.equal(request.post.callCount, 1);
           assert.equal(request.post.args[0][0].url, 'http://test/foo');
           assert.deepEqual(request.post.args[0][0].body, {some: 'data'});
-          assert.equal(request.post.args[0][0].json, true);
-          assert.deepEqual(request.post.args[0][0].headers, {
```
Comment (dianabarsan) [inline shared-libs/outbound/test/outbound.spec.js:344]: I generally prefer to keep test assertions with as much parameter coverage as possible, So here, instead of reducing coverage, can you please update the test to assert other potential headers too instead of reducing the assertion to just one header?

File: shared-libs/outbound/test/outbound.spec.js [hunk 10]
```diff
@@ -267,14 +268,15 @@ describe('outbound shared library', () => {
...
+      sinon.stub(environment, 'getVersion').resolves('4.18.0');
       sinon.stub(request, 'post').resolves();
 
       return outbound.__get__('sendPayload')(payload, conf)
         .then(() => {
           assert.equal(request.post.callCount, 1);
           assert.equal(request.post.args[0][0].url, 'http://test/foo');
           assert.deepEqual(request.post.args[0][0].body, {some: 'data'});
-          assert.equal(request.post.args[0][0].json, true);
+          assert.match(request.post.args[0][0].headers['user-agent'], /^CHT\/4\.18\.0/);
```
Comment (dianabarsan) [inline shared-libs/outbound/test/outbound.spec.js:279]: Can you please add a test where os.platform and arch are also stubbed, so we see the complete user agent header as well?

**Review by dianabarsan — COMMENTED** [review]
Very nice! Just a few minor requests inline :) Thanks for your patience.

**Review by dianabarsan — APPROVED** [review]
Approving to unblock this. Good luck!!
